version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: address-book-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1